# Generated by Django 3.1.6 on 2021-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='hello@gmail.com', max_length=256, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowano'), ('rejected', 'Odrzucono')], default='pending', editable=False, max_length=8),
        ),
    ]
