# Generated by Django 3.1.6 on 2021-02-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210223_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='hello2@gmail.com', max_length=256, verbose_name='e-mail'),
        ),
    ]
