# Generated by Django 3.1.6 on 2021-02-27 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_auto_20210225_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=256, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowano'), ('rejected', 'Odrzucono')], default='pending', max_length=8),
        ),
        
    ]
