# Generated by Django 3.1.6 on 2021-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.TextField(default='snippet', verbose_name='Snippet'),
            preserve_default=False,
        ),
    ]
