# Generated by Django 3.1.6 on 2021-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210313_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursworked',
            name='logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hoursworked',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
