# Generated by Django 3.1.6 on 2021-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210313_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursworked',
            name='finish',
            field=models.DateTimeField(null=True),
        ),
    ]
