# Generated by Django 3.1.6 on 2021-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210314_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursworked',
            name='hour_count',
            field=models.FloatField(default=0),
        ),
    ]
