# Generated by Django 3.1.6 on 2021-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20210314_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursworked',
            name='hour_count',
            field=models.DurationField(default=0),
        ),
    ]
