# Generated by Django 3.1.6 on 2021-03-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoursworked',
            options={'ordering': ['-day']},
        ),
        migrations.AddField(
            model_name='profile',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
