# Generated by Django 3.1.6 on 2021-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20210318_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
