# Generated by Django 3.1.6 on 2021-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20210323_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
