# Generated by Django 3.1.6 on 2021-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_auto_20210324_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursworked',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
