# Generated by Django 3.1.6 on 2021-03-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_hoursworked_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursworked',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
