# Generated by Django 3.1.6 on 2021-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowano'), ('rejected', 'Odrzucono')], default='accepted', max_length=8),
        ),
    ]
