# Generated by Django 3.1.6 on 2021-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20210327_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursworked',
            name='salary',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
