# Generated by Django 3.1.6 on 2021-03-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_payslip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-month']},
        ),
    ]
