# Generated by Django 3.1.6 on 2021-03-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0040_auto_20210329_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
