# Generated by Django 3.1.6 on 2021-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_auto_20210401_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.DateField(null=True),
        ),
    ]
