# Generated by Django 3.1.6 on 2021-04-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0043_auto_20210401_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
