# Generated by Django 3.1.6 on 2021-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0044_auto_20210401_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.DateField(),
        ),
    ]
