# Generated by Django 3.1.6 on 2021-04-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_auto_20210401_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursworked',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
